### ISSUE TITLE
Protocol buffers test skewed by Joda LocalDate string conversions

### ISSUE THREAD

**Issue by phensley** [egillespie/performance-playground#7]
I ran the benchmark under a profiler and noticed the Protobuf side of the test was dominated by Joda string conversions.  The Jackson converter uses the `LocalDate` numeric fields directly, which is far more efficient than formatting / parsing strings on the Protocol Buffers side.  Given the large number of `LocalDate` fields this makes the PB benchmark perform far slower.

I put together a quick test consisting of only basic types and found proto3 to be about 5 times faster than Jackson on both serialization and deserialization.  My results are here: https://github.com/phensley/protobuf-vs-jackson

**Comment by egillespie** [comment]
Nice catch! Which profiler did you use? I'd like to reproduce your findings before fixing the date conversion code.

**Comment by phensley** [comment]
No problem -- I used the Oracle VisualVM cpu profiler. It has a "hot spots" view.

**Comment by egillespie** [comment]
I swapped out LocalDate and the String conversion with Instant and millis. As @phensley noticed, this was majorly skewing the results in favor of Jackson and this change totally flips the results of the benchmarks! :+1: 

Shame on me for not paying better attention to the serialized data too, I should have noticed that the Joda Time module was converting LocalDate to number parts instead of to a String. :frowning:

**Comment by krishna81m** [comment]
Are the conclusions in the main page still applicable that https://code.google.com/p/protobuf-json/ is much faster than FasterXML Jackson library? I am a bit confused if we are comparing the right data as your article says "JSON" serializers/deserializers comparison.

**Comment by egillespie** [comment]
@krishna81m Based on the last execution of the tests, Google Protocol Buffers is serializing faster than Jackson JSON, even with Afterburner.

Anywhere that I use the term "JSON" is specific to Jackson. Most of the time I even use the fully-qualified term "Jackson JSON" to try to make it clear that the tests are comparing the performance of the library serialization and deserialization into their respective data formats.
